name: emmetcli
description: A command-line application to generate a recap documentation from flutter/dart test projects. 
version: 1.0.0+7
author: Apparence.io
homepage: https://github.com/Apparence-io/emmet-cli

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  emmet: ^0.0.1+4
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
