name: emmetcli
description: A sample command-line application.
version: 1.0.0
# homepage: https://example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  emmet: ^0.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
